### ISSUE TITLE
Add context from the announcement post to the README for clarity

### ISSUE THREAD

**Issue by bpartridge** [Automattic/stream-builder#5]
https://engineering.tumblr.com/post/722102563011493888/streambuilder-our-open-source-framework-for has a lot of great context on why this is an exciting framework, but it's missing from the README. As such, it's very hard to know what this repository is for, if someone comes across this repository directly and not through the post. Some of that content should be added here!

(Also - amazing work on this, all! Coincidentally, we're also working on a ranker-interleaving system at my travel startup, and it's incredibly timely to see that others are approaching these complex problems in similar ways.)

**Comment by cyle** [comment]
Hey, thanks, yes, that's a great idea. We'll add that!
